<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>9e333161-a593-4e7d-9425-d903d37eeab0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#scrollToTopBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='scrollToTopBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5feb6edf-4728-413d-88cc-25f7aba02fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scrollToTopBtn</value>
      <webElementGuid>40fee27d-7420-4412-a465-7ab9a7330216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>scrolling-scroll-to-top</value>
      <webElementGuid>9507201e-0e8a-4e7a-98b3-092d24a7a630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>↑</value>
      <webElementGuid>c3cb41f4-2e81-440d-b837-4fbc6c70b65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTopBtn&quot;)</value>
      <webElementGuid>e861e4d9-e808-4882-bbce-9a5b3fd0611b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='scrollToTopBtn']</value>
      <webElementGuid>9651441e-9921-4508-a686-a26bcf4f91c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scroll to Top Button'])[1]/following::button[1]</value>
      <webElementGuid>d242bc16-0019-43cc-9896-b3939cf8f696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Scrollbar'])[1]/following::button[1]</value>
      <webElementGuid>ada2ddd4-d71a-4b1a-9b5c-24721b1bf284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parallax Scrolling'])[1]/preceding::button[1]</value>
      <webElementGuid>18e5238e-9465-4510-8a2a-192dad88ed74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Links'])[1]/preceding::button[1]</value>
      <webElementGuid>e46bf33b-4930-42b3-8405-3b8283a0337f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='↑']/parent::*</value>
      <webElementGuid>1e56c50a-3305-4cda-9ad7-6f73b0fc9fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/button</value>
      <webElementGuid>f9a05128-ea19-4e1f-ae5a-2d38d4fa1998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'scrollToTopBtn' and (text() = '↑' or . = '↑')]</value>
      <webElementGuid>aad9b63b-dbb7-49df-806d-4935a5babcba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
